#!/usr/bin/env bash

PAGER=${PAGER:-"nvim -nR -i /dev/null --clean"}
TERMINAL="alacritty --embed"
PICTURES_DIR=$(xdg-user-dir PICTURES)

start_tabbed () {
	FIFO="$(mktemp -u)"
	mkfifo "$FIFO"

	tabbed > "$FIFO" &

	jobs # Get rid of the "Completed" entries

	TABBEDPID="$(jobs -p %%)"

	if [ -z "$TABBEDPID" ] ; then
		echo "Can't start tabbed"
		exit 1
	fi

	read -r XID < "$FIFO"

	rm -- "$FIFO"
}

get_viewer_pid () {
	VIEWERPID="$(jobs -p %%)"
}

kill_viewer () {
	if [ -n "$VIEWERPID" ] && jobs -p | grep "$VIEWERPID" ; then
		kill "$VIEWERPID"
	fi
}

sigint_kill () {
	kill_viewer
	kill "$TABBEDPID"
	exit 0
}

previewer_loop () {
	unset -v NNN_FIFO
	# mute from now
	exec >/dev/null 2>&1

	start_tabbed
	trap sigint_kill SIGINT

	while read -r FILE ; do

		jobs # Get rid of the "Completed" entries

		if ! jobs | grep tabbed ; then
			break
		fi

		if [ ! -e "$FILE" ] ; then
			continue
		fi

		kill_viewer

		MIME="$(file -bL --mime-type "$FILE")"

		case "$MIME" in
			inode/directory)
				if [[ "$FILE" == "$PICTURES_DIR"* ]]; then
					if \ls -f "$FILE" | grep -qm 1 "jpg$\|jpeg$\|png$\|svg$\|gif$\|jxl$\|webp$\|ico$\|bmp$"; then
						XDG_CACHE_HOME="$XDG_RUNTIME_DIR" nsxiv -te "$XID" "$FILE" &
					else
						$TERMINAL "$XID" -e nnn "$FILE" &
					fi
				else
					$TERMINAL "$XID" -e nnn "$FILE" &
				fi
				;;
			video/*) mpv --mute=yes --force-window=immediate --loop-file --wid="$XID" "$FILE" & ;;
			audio/*) mpv --force-window=immediate --loop-file --wid="$XID" "$FILE" & ;;
			image/*) nsxiv -ae "$XID" "$FILE" & ;;
			application/pdf) zathura -e "$XID" "$FILE" & ;;
			text/*) $TERMINAL "$XID" -e $PAGER "$FILE" & ;;
			*) $TERMINAL "$XID" -e sh -c "file '$FILE' | $PAGER -" & ;;
		esac
		get_viewer_pid

	done
	kill "$TABBEDPID"
	kill_viewer
}

if [ ! -r "$NNN_FIFO" ] ; then
	echo "Can't read \$NNN_FIFO ('$NNN_FIFO')"
	exit 1
fi

previewer_loop < "$NNN_FIFO" &
disown
